# project_path = '''/home/davide/Documents/Exabeat/aggregator/exabeat'''
project_path = '''/home/davide/Documents/Exabeat/aggregator/IPEBDCO'''
branch_to_merge = '''origin/develop_newpom'''
#branch_to_merge = '''origin/feature/upgrade-to-cdh-5.16-IEB_1.70.X'''
issue_pattern = r'''IEB[_-](\d+)'''
